
# 本可用区zone(一般指机房)标识
zone = "zone1"

# 同一discovery集群的所有node节点地址，包含本node
nodes = ["10.9.141.21:7171"]

# 其他可用区zone访问host和其标识
# "addr" = "zone name"
# [zones]
# "127.0.0.2:7172" = "zone3"

# 本节点监听端口
# 0.0.0.0
[httpServer]
addr = "0.0.0.0:7171"

# 当前节点同步其他节点使用的http client
# dial 连接建立超时时间
# keepAlive 连接复用保持时间
[httpClient]
dial = "1s"
keepAlive = "120s"
