version: "3"
services:
  discovery:
    image: discovery:latest
    command: ./discovery -conf discovery-example.toml
    volumes:
      - ./discovery-example.toml:/data/discovery-example.toml
    ports:
      - "7171:7171"
    environment:
      - ENV=test
    network_mode: bridge
    restart: always
